CREATE TABLE ACCOUNT (
    ID BIGINT NOT NULL ,
    ACCOUNT_NUMBER VARCHAR(32),
    LABEL VARCHAR(128),
    PRIMARY KEY(ID)
);

CREATE INDEX ACCOUNT_ACCOUNTIDX ON ACCOUNT USING hash(ACCOUNT_NUMBER);

COMMENT ON TABLE ACCOUNT IS 'Счета';
COMMENT ON COLUMN ACCOUNT.ID IS 'идентификатор записи';
COMMENT ON COLUMN ACCOUNT.ACCOUNT_NUMBER IS 'Номер счета';
COMMENT ON COLUMN ACCOUNT.LABEL IS 'Имя счета';
